[project]
name = "ansiblecollection-proxmox"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ansible-core>=2.19.0",
    "ansible-lint>=25.8.2",
    "proxmoxer>=2.2.0",
    "requests>=2.32.5",
]
